### ISSUE TITLE
Housekeeping

### ISSUE THREAD

**Issue by zstumgoren** [stanfordjournalism/padj23-code#2]
This repo was created largely from the old Programming in Journalism course repo.

A bunch of pages need to be deleted, added (to complete the transition), or updated to generalize the content and take into account:

- the migration of basic Python instruction [Data Journalism Notebooks](https://stanfordjournalism.github.io/data-journalism-notebooks/lab/) (running on JupyterLite).
- The use of GitHub Classroom and Codespaces for various assignments

## Tasks

- [x] Update [assignments](https://github.com/stanfordjournalism/padj-code/tree/main/assignments) to point to JupyterLite (and or mention that we're using GH Classrooms and Codespaces to manage the basics
- [x] Add Senate Compromisers assignment from [stanford-progj-23](https://github.com/stanfordjournalism/stanford-progj-2023/blob/main/assignments/senate_compromisers.md) and solution from [zstumgoren/stanford-prog-22-solutions](https://github.com/zstumgoren/stanford-progj-2022-solutions/tree/main/propub_senate_api) to padj-code and padj-code-solutions, respectively (note, don't seem to have committed solution to 2023 repo so use 2022)
- [ ] Generally review and transfer [progj 23 assignments](https://github.com/stanfordjournalism/stanford-progj-2023/blob/main/assignments/) and solutions to padj-code and padj-code-solutions (for solutions, we should check 2022 and possibly earlier repos on my personal account)
